@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueGuestList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueGuestList
UniqueTagList -[hidden]down- UniqueGuestList

UniqueTagList -right-> "*" Tag
UniqueGuestList -right-> Guest

Guest -up-> "*" Tag

Guest *--> Name
Guest *--> Phone
Guest *--> Email
Guest *--> Address
@enduml
