@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

GuestNote *-right-> "1" UniqueGuestList
GuestNote *-right-> "1" UniqueRequestList
UniqueRequestList -[hidden]down- UniqueGuestList
UniqueRequestList -[hidden]down- UniqueGuestList

UniqueRequestList -right-> "*" Request
UniqueGuestList -right-> Guest

Guest -up-> "*" Request

Guest *--> Name
Guest *--> Phone
Guest *--> Email
Guest *--> RoomNumber
Guest *--> Status
@enduml
